apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
spec:
  selector:
    app: sample-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
