apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
spec:
  selector:
    app: sample-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
